### ISSUE TITLE
使用@tiptap/vue-3集成的时候报错

### ISSUE THREAD

**Issue by bbbbbbbbbbbbba** [syfxlin/tiptap-starter-kit#28]
错误信息：
```
TypeError: Cannot read properties of undefined (reading 'name')
    at Object.addStorage (sup.ts:47:43)
    at callOrReturn (chunk-BBK5O6IW.js?v=25d5505f:474:12)
    at new _Mark (chunk-BBK5O6IW.js?v=25d5505f:4039:20)
    at _Mark.extend (chunk-BBK5O6IW.js?v=25d5505f:4060:23)
    at _Mark.configure (chunk-BBK5O6IW.js?v=25d5505f:4048:28)
    at configure (functions.ts:22:28)
    at Object.addExtensions (index.ts:112:5)
    at chunk-BBK5O6IW.js?v=25d5505f:1051:44
    at Array.map (<anonymous>)
    at _ExtensionManager.flatten (chunk-BBK5O6IW.js?v=25d5505f:1043:23)
```

**Comment by syfxlin** [comment]
请提供最小实现以及复现步骤，从错误信息看不出原因。

**Comment by bbbbbbbbbbbbba** [comment]
> 请提供最小实现以及复现步骤，从错误信息看不出原因。

感谢回复，我整理下发给你。 稍等。

**Comment by bbbbbbbbbbbbba** [comment]
> 请提供最小实现以及复现步骤，从错误信息看不出原因。

hi，我整理了下实现， 您看下： https://stackblitz.com/edit/vitejs-vite-grdsan?file=src%2FApp.vue

<img width="1588" alt="image" src="https://github.com/user-attachments/assets/d8f23220-9830-4164-94c3-983b0dba761c">

**Comment by syfxlin** [comment]
Hi @bbbbbbbbbbbbba, 这是 Tiptap 引入的 Bug，会导致 options 被设置成错误的值，引起这个错误。可以把 Tiptap 相关的版本升级到 2.5.4 解决。

https://github.com/ueberdosis/tiptap/commit/07f4c03315f91b1c597ff764b395a488514a9036#diff-c17789a64b74bdd437c357796b400a72ba9e777d4df45d7654c1e0164b67dcf6L591-L598
